name: Dependency
on: [push]
jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Download test dependencies
      uses: teddyking/dependency-action@master
      with:
        deps: https://dep1.tar.gz,https://dep2.txz
    - name: Run tests
